# Generated by Django 3.1.3 on 2021-02-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20200412_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coopmember',
            options={'verbose_name': 'membership', 'verbose_name_plural': 'memberships'},
        ),
        migrations.AlterField(
            model_name='coopmember',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='coopmember',
            name='civil_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widow(ed)')], max_length=1, verbose_name='civil status'),
        ),
        migrations.AlterField(
            model_name='coopmember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='coopmember',
            name='national_id',
            field=models.CharField(max_length=255, verbose_name='National id'),
        ),
        migrations.AlterField(
            model_name='coopmember',
            name='nationality',
            field=models.CharField(max_length=255, verbose_name='nationality'),
        ),
    ]
