# Generated by Django 3.1.3 on 2021-02-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20210205_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coopmember',
            options={'verbose_name': 'socio', 'verbose_name_plural': 'socios'},
        ),
        migrations.AlterField(
            model_name='coopmember',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='coopmember',
            name='civil_status',
            field=models.CharField(choices=[('S', 'Soltero/a'), ('M', 'Casado/a'), ('D', 'Divorciado/a'), ('W', 'Viudo/a')], max_length=1, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='coopmember',
            name='gender',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('O', 'Other')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='coopmember',
            name='national_id',
            field=models.CharField(max_length=255, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='coopmember',
            name='nationality',
            field=models.CharField(max_length=255, verbose_name='Nacionalidad'),
        ),
    ]
