# Generated by Django 3.0.5 on 2020-04-06 21:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('De', 'Delivered'), ('Ch', 'Charged'), ('Pl', 'Planned'), ('Ca', 'Cancelled')], default='Pl', max_length=2)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.CoopMember')),
            ],
            options={
                'verbose_name': 'basket',
                'verbose_name_plural': 'baskets',
            },
        ),
        migrations.CreateModel(
            name='BasketSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('I', 'Inactive')], default='P', max_length=1)),
                ('valid_from', models.DateTimeField(default=datetime.datetime.now, verbose_name='Valid from')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid until')),
                ('admin_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Admin fee')),
                ('advance_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Advance fee')),
            ],
            options={
                'verbose_name': 'basket subscription',
                'verbose_name_plural': 'basket subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PickupPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('pickup_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='pickup day')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=10800), verbose_name='duration')),
            ],
            options={
                'verbose_name': 'pickup place',
                'verbose_name_plural': 'pickup places',
            },
        ),
        migrations.CreateModel(
            name='ProduceUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Unit fee')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPeriodicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'periodicity',
                'verbose_name_plural': 'periodicities',
            },
        ),
        migrations.CreateModel(
            name='PickupOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=10800), verbose_name='duration')),
                ('status', models.CharField(max_length=100)),
                ('week_type', models.CharField(choices=[('A', 'Odd week'), ('B', 'Even week')], default='A', max_length=1)),
                ('pickup_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.PickupPlace', verbose_name='pickup place')),
            ],
            options={
                'verbose_name': 'pickup occurrence',
                'verbose_name_plural': 'pickup occurrences',
            },
        ),
        migrations.CreateModel(
            name='BasketSubscriptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.ProduceUnit', verbose_name='produce')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.BasketSubscription')),
            ],
            options={
                'verbose_name': 'basket subscription item',
                'verbose_name_plural': 'basket subscription items',
            },
        ),
        migrations.AddField(
            model_name='basketsubscription',
            name='contents',
            field=models.ManyToManyField(through='delivery.BasketSubscriptionItem', to='delivery.ProduceUnit'),
        ),
        migrations.AddField(
            model_name='basketsubscription',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.CoopMember', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='basketsubscription',
            name='periodicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.SubscriptionPeriodicity', verbose_name='periodicity'),
        ),
        migrations.AddField(
            model_name='basketsubscription',
            name='pickup_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.PickupPlace', verbose_name='pickup place'),
        ),
        migrations.CreateModel(
            name='BasketContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Basket')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.ProduceUnit')),
            ],
        ),
        migrations.CreateModel(
            name='BasketChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pe', 'Pending'), ('Ap', 'Approved'), ('Re', 'Rejected'), ('Fi', 'Finalised')], default='Pe', max_length=2)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.CoopMember')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='pickup_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.PickupOccurrence', verbose_name='Pickup day'),
        ),
    ]
