# Generated by Django 3.0.5 on 2020-04-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketsubscription',
            options={'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AddField(
            model_name='basketsubscription',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Total fee'),
        ),
        migrations.AddField(
            model_name='basketsubscriptionitem',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=1100, max_digits=8, verbose_name='fee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickupplace',
            name='pickup_day',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='pickup day'),
        ),
    ]
