# Generated by Django 3.0.5 on 2020-04-16 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20200412_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketsubscription',
            name='contents',
        ),
        migrations.AlterField(
            model_name='basketsubscriptionitem',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='delivery.BasketSubscription'),
        ),
    ]
