# Generated by Django 3.1.3 on 2021-02-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20200416_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupplace',
            name='pickup_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='pickup day'),
        ),
    ]
